"""separat seller table

Revision ID: 03bd0a650f8b
Revises: 3d2f90e61220
Create Date: 2024-12-07 15:10:57.410987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03bd0a650f8b'
down_revision: Union[str, None] = '3d2f90e61220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('BIC', sa.Integer(), nullable=False),
    sa.Column('banking_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IBAN', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sales_tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'role')
    op.drop_column('user', 'forename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('forename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'first_name')
    op.drop_table('seller')
    op.drop_table('role')
    # ### end Alembic commands ###
