"""updated user with tax field

Revision ID: 1dee877a0c03
Revises: 8bae2756fdb2
Create Date: 2024-11-28 09:44:54.049982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dee877a0c03'
down_revision: Union[str, None] = '8bae2756fdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('publisher', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('sales_tax_id', sa.Integer(), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'sales_tax_id')
    op.drop_column('user', 'password_hash')
    op.alter_column('publisher', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('genre', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
