"""Deleted Tokentable

Revision ID: 2ac482621f1b
Revises: 497d3cef5a09
Create Date: 2024-12-30 12:39:38.153589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ac482621f1b'
down_revision: Union[str, None] = '497d3cef5a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokentable')
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.create_table('tokentable',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tokentable_user_id_fkey'),
    sa.PrimaryKeyConstraint('access_token', name='tokentable_pkey')
    )
    # ### end Alembic commands ###
