"""Author email

Revision ID: 2e84b5da69ac
Revises: 5b46635ace9b
Create Date: 2025-01-03 16:23:21.393583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e84b5da69ac'
down_revision: Union[str, None] = '5b46635ace9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
