"""image in books

Revision ID: 497d3cef5a09
Revises: dba68ee2b71c
Create Date: 2024-12-22 21:08:05.606002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497d3cef5a09'
down_revision: Union[str, None] = 'dba68ee2b71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'image')
    # ### end Alembic commands ###
