"""disabled in user deleted

Revision ID: 4d3e6748abeb
Revises: 0894e464b15f
Create Date: 2024-12-31 12:19:24.195190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3e6748abeb'
down_revision: Union[str, None] = '0894e464b15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
