"""user phone number

Revision ID: 5b46635ace9b
Revises: b506fe71478b
Create Date: 2025-01-02 10:40:43.862677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5b46635ace9b'
down_revision: Union[str, None] = 'b506fe71478b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.add_column('order_item', sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('order_item_isbn_fkey', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'book', ['product_id'], ['isbn'])
    op.drop_column('order_item', 'isbn')
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'phone_number')
    op.add_column('order_item', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_isbn_fkey', 'order_item', 'book', ['isbn'], ['isbn'])
    op.drop_column('order_item', 'product_id')
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
