"""update tables 2.0

Revision ID: 8bae2756fdb2
Revises: 977e7a48e0d0
Create Date: 2024-11-13 13:45:52.166280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8bae2756fdb2'
down_revision: Union[str, None] = '977e7a48e0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genre', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('genre', 'genre')
    op.add_column('publisher', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('publisher', 'publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publisher', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('publisher', 'name')
    op.add_column('genre', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('genre', 'name')
    # ### end Alembic commands ###
