"""disabled in user

Revision ID: b506fe71478b
Revises: 4d3e6748abeb
Create Date: 2024-12-31 13:04:35.263074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b506fe71478b'
down_revision: Union[str, None] = '4d3e6748abeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'disabled')
    op.alter_column('book', 'image',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
