"""gibt nur User, Rolle über id

Revision ID: dba68ee2b71c
Revises: 98482c7ed0bb
Create Date: 2024-12-22 16:40:18.481117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dba68ee2b71c'
down_revision: Union[str, None] = '98482c7ed0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    op.add_column('user', sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('BIC', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('banking_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('IBAN', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('sales_tax_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sales_tax_id')
    op.drop_column('user', 'IBAN')
    op.drop_column('user', 'banking_name')
    op.drop_column('user', 'BIC')
    op.drop_column('user', 'bank')
    op.create_table('seller',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bank', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('BIC', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('banking_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('IBAN', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sales_tax_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='seller_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='seller_pkey')
    )
    # ### end Alembic commands ###
